### ISSUE TITLE
Run queries in order

### ISSUE THREAD

**Issue by calebevans** [RedHatQE/qe-metrics#82]
Because there are times when a bug could show up in both the `blocker` and `critical-blocker` queries, we would like to add functionality to ensure the queries are run in this order:

1. `blocker`
2. `critical-blocker`

Running it this way will ensure that if the issue is a result in both queries, it is assigned as `critical-blocker`

**Comment by myakove** [comment]
Why not just have them both? 
In Grafana, we can filter by severity, this way we don't mess with the data
