### ISSUE TITLE
Use `function_runner_with_pdb`, this will enter `pdb` when `--pdb` passed - 84

### ISSUE THREAD

**Issue by redhat-qe-bot2** [RedHatQE/qe-metrics#85]
[Auto generated]
Number: [#84]

**Comment by redhat-qe-bot1** [comment]
[1;37mqe-metrics[1;0m(2QnhW)[PR 84]: Closing issue for PR: Use `function_runner_with_pdb`, this will enter `pdb` when `--pdb` passed.
PR was closed.
